<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MigrationStudio.Application\MigrationStudio.Application.csproj" />
    <ProjectReference Include="..\MigrationStudio.Domain\MigrationStudio.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="PDFsharp-MigraDoc" />
  </ItemGroup>

</Project>
