using System.Collections.ObjectModel;
using CommunityToolkit.Mvvm.ComponentModel;
using CommunityToolkit.Mvvm.Input;
using MigrationStudio.Application.Conversion;
using MigrationStudio.Application.DataMigration;
using MigrationStudio.Application.Deployment;
using MigrationStudio.Application.Discovery;
using MigrationStudio.Application.Navigation;
using MigrationStudio.Application.Reporting;
using MigrationStudio.Application.Validation;
using MigrationStudio.Desktop.Dialogs;
using MigrationStudio.Desktop.Navigation;
using MigrationStudio.Domain.Reporting;
using MigrationStudio.Domain.Validation;

namespace MigrationStudio.Desktop.ViewModels;

public sealed partial class ReportsViewModel : ObservableObject
{
    private readonly IInventorySession _inventory;
    private readonly IConversionSession _conversion;
    private readonly IDataMigrationSession _dataMigration;
    private readonly IDeploymentSession _deployment;
    private readonly IValidationSession _validation;
    private readonly IMigrationReportCoordinator _reportCoordinator;
    private readonly IMigrationReportEngine _reports;
    private readonly IManualReviewStore _manualReviewStore;
    private readonly IRunHistoryStore _historyStore;
    private readonly ISanitizedLogExporter _logExporter;
    private readonly IFileDialogService _dialogs;
    private readonly IDesktopNavigationService _navigation;

    [ObservableProperty] private string _status = "Load current runs or open run history to begin.";
    [ObservableProperty] private bool _isBusy;
    [ObservableProperty] private double _progress;
    [ObservableProperty] private string _sourceServer = "Not recorded";
    [ObservableProperty] private string _targetServer = "Not recorded";
    [ObservableProperty] private string _organizationName = string.Empty;
    [ObservableProperty] private string _projectName = "SQL Server to PostgreSQL Migration";
    [ObservableProperty] private string _reportTitle = "Migration Executive Summary";
    [ObservableProperty] private string _preparedBy = string.Empty;
    [ObservableProperty] private string _reviewedBy = string.Empty;
    [ObservableProperty] private string _classificationMarking = "Internal";
    [ObservableProperty] private string _footer = "Generated by SQL Server to PostgreSQL Migration Studio";
    [ObservableProperty] private string _logoPath = string.Empty;
    [ObservableProperty] private bool _useDarkDashboardTheme;
    [ObservableProperty] private string _overallStatus = "No validation run";
    [ObservableProperty] private int _objectCount;
    [ObservableProperty] private long _rowsWritten;
    [ObservableProperty] private int _deploymentFailures;
    [ObservableProperty] private int _criticalBlockers;
    [ObservableProperty] private int _openManualReviews;
    [ObservableProperty] private ManualReviewRowViewModel? _selectedManualReview;
    [ObservableProperty] private bool _showOnlyUnresolved = true;
    [ObservableProperty] private RunHistoryEntry? _selectedHistoryRun;
    [ObservableProperty] private string _lastReportDirectory = string.Empty;

    public ReportsViewModel(
        IInventorySession inventory,
        IConversionSession conversion,
        IDataMigrationSession dataMigration,
        IDeploymentSession deployment,
        IValidationSession validation,
        IMigrationReportCoordinator reportCoordinator,
        IMigrationReportEngine reports,
        IManualReviewStore manualReviewStore,
        IRunHistoryStore historyStore,
        ISanitizedLogExporter logExporter,
        IFileDialogService dialogs,
        IDesktopNavigationService navigation)
    {
        _inventory = inventory;
        _conversion = conversion;
        _dataMigration = dataMigration;
        _deployment = deployment;
        _validation = validation;
        _reportCoordinator = reportCoordinator;
        _reports = reports;
        _manualReviewStore = manualReviewStore;
        _historyStore = historyStore;
        _logExporter = logExporter;
        _dialogs = dialogs;
        _navigation = navigation;
        RefreshDashboard();
    }

    public string Title { get; } = "Migration dashboard and reports";

    public IReadOnlyList<ManualReviewStatus> ManualReviewStatuses { get; } =
        Enum.GetValues<ManualReviewStatus>();

    public ObservableCollection<ManualReviewRowViewModel> ManualReviews { get; } = [];

    public ObservableCollection<ManualReviewRowViewModel> VisibleManualReviews { get; } = [];

    public ObservableCollection<RunHistoryEntry> RunHistory { get; } = [];

    public ObservableCollection<string> ReportFiles { get; } = [];

    [RelayCommand]
    private async Task RefreshAsync()
    {
        try
        {
            IsBusy = true;
            RefreshDashboard();
            await LoadManualReviewsAsync();
            await LoadHistoryAsync();
            Status = "Dashboard refreshed from current sessions and persisted history.";
        }
        finally
        {
            IsBusy = false;
        }
    }

    [RelayCommand]
    private async Task GenerateReportAsync()
    {
        if (_inventory.Current is null)
        {
            Status = "A discovery inventory is required before generating a report.";
            return;
        }
        var parent = _dialogs.SelectFolder("Select a parent folder for the Reports package");
        if (parent is null)
        {
            return;
        }
        try
        {
            IsBusy = true;
            Progress = 0;
            var reporter = new Progress<ReportGenerationProgress>(item =>
            {
                Progress = item.Percentage;
                Status = $"{item.Stage}: {item.CurrentFile}";
            });
            var result = await _reportCoordinator.GenerateAsync(
                CreateRequestOptions(), parent, reporter, CancellationToken.None);
            LastReportDirectory = result.ReportsDirectory;
            ReportFiles.Clear();
            foreach (var file in result.Files)
            {
                ReportFiles.Add(file);
            }
            await LoadHistoryAsync();
            Status = $"Generated {result.Files.Count} sanitized report artifacts in {result.ReportsDirectory}.";
        }
        catch (Exception exception)
        {
            Status = $"Report generation failed: {exception.Message}";
        }
        finally
        {
            IsBusy = false;
        }
    }

    [RelayCommand]
    private async Task SynchronizeFindingsAsync()
    {
        var existing = (await _manualReviewStore.LoadAsync(CancellationToken.None))
            .ToDictionary(item => item.FindingKey, StringComparer.OrdinalIgnoreCase);
        var candidates = new List<ManualReviewItem>();
        if (_conversion.Current is not null)
        {
            candidates.AddRange(_conversion.Current.Artifacts.Where(item => item.RequiresManualReview)
                .Select(item => NewReview(
                    $"conversion:{item.ContentHash}",
                    item.TargetObjectId.QualifiedName,
                    $"Conversion review: {item.TargetObjectId.QualifiedName}",
                    string.Join("; ", item.Findings.Select(finding => finding.Message)),
                    item.Classification == Domain.Inventory.ConversionClassification.Unsupported,
                    item.PostgreSqlDefinition)));
        }
        if (_validation.Current is not null)
        {
            candidates.AddRange(_validation.Current.Findings.Where(item =>
                    item.Classification == ComparisonClassification.ManualReview ||
                    item.Severity is ValidationSeverity.Critical or ValidationSeverity.Error)
                .Select(item => NewReview(
                    $"validation:{item.RuleId}:{item.SourceObject}",
                    item.SourceObject,
                    item.Summary,
                    item.Summary,
                    item.Severity == ValidationSeverity.Critical,
                    item.TargetDefinition)));
        }
        foreach (var candidate in candidates.Where(item => !existing.ContainsKey(item.FindingKey)))
        {
            await _manualReviewStore.SaveAsync(candidate, CancellationToken.None);
        }
        await LoadManualReviewsAsync();
        Status = $"Manual-review workflow synchronized; {ManualReviews.Count} items recorded.";
    }

    [RelayCommand]
    private async Task SaveManualReviewAsync()
    {
        if (SelectedManualReview is null)
        {
            return;
        }
        try
        {
            await _manualReviewStore.SaveAsync(
                SelectedManualReview.ToRecord(), CancellationToken.None);
            await LoadManualReviewsAsync();
            Status = "Manual-review decision saved.";
        }
        catch (Exception exception)
        {
            Status = $"Manual-review update rejected: {exception.Message}";
        }
    }

    [RelayCommand]
    private async Task ReopenManualReviewAsync()
    {
        if (SelectedManualReview is null)
        {
            return;
        }
        try
        {
            await _manualReviewStore.ReopenAsync(
                SelectedManualReview.Id,
                string.IsNullOrWhiteSpace(SelectedManualReview.Comments)
                    ? "Reopened from migration dashboard."
                    : SelectedManualReview.Comments,
                CancellationToken.None);
            await LoadManualReviewsAsync();
            Status = "Manual-review item reopened.";
        }
        catch (Exception exception)
        {
            Status = $"Manual-review item could not be reopened: {exception.Message}";
        }
    }

    [RelayCommand]
    private async Task ExportSanitizedLogsAsync()
    {
        var directory = _dialogs.SelectFolder("Select a folder for sanitized logs");
        if (directory is null)
        {
            return;
        }
        var ids = RunHistory.Select(item => item.RunId).ToHashSet();
        var path = await _logExporter.ExportAsync(directory, ids, CancellationToken.None);
        Status = $"Sanitized logs exported to {path}.";
    }

    [RelayCommand]
    private async Task OpenHistoricalRunAsync()
    {
        if (SelectedHistoryRun is null)
        {
            return;
        }
        var record = await _historyStore.LoadAsync(SelectedHistoryRun.RunId, CancellationToken.None);
        Status = record is null
            ? "The selected historical run is unavailable."
            : $"Opened {record.Entry.Kind} run {record.Entry.RunId}; payload schema is available for report regeneration.";
    }

    [RelayCommand]
    private async Task RegenerateHistoricalReportAsync()
    {
        if (SelectedHistoryRun is null)
        {
            return;
        }
        if (SelectedHistoryRun.Kind != RunHistoryKind.ReportGeneration)
        {
            Status = "Select a report-generation run to regenerate its historical package.";
            return;
        }
        var parent = _dialogs.SelectFolder("Select a parent folder for the regenerated Reports package");
        if (parent is null)
        {
            return;
        }
        try
        {
            IsBusy = true;
            Progress = 0;
            var reporter = new Progress<ReportGenerationProgress>(item =>
            {
                Progress = item.Percentage;
                Status = $"{item.Stage}: {item.CurrentFile}";
            });
            var result = await _reports.RegenerateAsync(
                SelectedHistoryRun.RunId, parent, reporter, CancellationToken.None);
            LastReportDirectory = result.ReportsDirectory;
            ReportFiles.Clear();
            foreach (var file in result.Files)
            {
                ReportFiles.Add(file);
            }
            await LoadHistoryAsync();
            Status = $"Regenerated historical report as run {result.ReportRunId}.";
        }
        catch (Exception exception)
        {
            Status = $"Historical report regeneration failed: {exception.Message}";
        }
        finally
        {
            IsBusy = false;
        }
    }

    [RelayCommand]
    private void OpenWorkspace() => _navigation.Navigate(NavigationRoute.Workspace);

    partial void OnShowOnlyUnresolvedChanged(bool value) => ApplyManualReviewFilter();

    private MigrationReportRequestOptions CreateRequestOptions() =>
        new()
        {
            SourceServer = SourceServer,
            TargetServer = TargetServer,
            Template = new ReportTemplate
            {
                TemplateId = UseDarkDashboardTheme ? "dashboard-dark" : "professional-light",
                OrganizationName = OrganizationName,
                ProjectName = ProjectName,
                ReportTitle = ReportTitle,
                PreparedBy = PreparedBy,
                ReviewedBy = ReviewedBy,
                ClassificationMarking = ClassificationMarking,
                Footer = Footer,
                LogoPath = string.IsNullOrWhiteSpace(LogoPath) ? null : LogoPath,
                UseDarkDashboardTheme = UseDarkDashboardTheme
            },
            ManualReviews = ManualReviews.Select(item => item.ToRecord()).ToArray(),
            ApplicationVersion = typeof(ReportsViewModel).Assembly.GetName().Version?.ToString() ?? "1.0.0"
        };

    private void RefreshDashboard()
    {
        ObjectCount = _inventory.Current?.Objects.Count(item => item.IsIncluded) ?? 0;
        RowsWritten = _dataMigration.CurrentResult?.Tables.Sum(item => item.RowsWritten) ?? 0;
        DeploymentFailures = _deployment.Result?.Failures.Count ?? 0;
        CriticalBlockers = _validation.Current?.Readiness.CriticalBlockers.Count ?? 0;
        OverallStatus = _validation.Current?.Readiness.OverallStatus.ToString() ??
                        _deployment.Result?.Status.ToString() ??
                        _dataMigration.CurrentResult?.State.ToString() ??
                        (_conversion.Current is null ? "No active run" : "Converted");
    }

    private async Task LoadManualReviewsAsync()
    {
        ManualReviews.Clear();
        foreach (var item in await _manualReviewStore.LoadAsync(CancellationToken.None))
        {
            ManualReviews.Add(new ManualReviewRowViewModel(item));
        }
        OpenManualReviews = ManualReviews.Count(item =>
            item.Status is ManualReviewStatus.Open or ManualReviewStatus.InProgress);
        ApplyManualReviewFilter();
    }

    private void ApplyManualReviewFilter()
    {
        VisibleManualReviews.Clear();
        foreach (var item in ManualReviews.Where(item =>
                     !ShowOnlyUnresolved ||
                     item.Status is ManualReviewStatus.Open or ManualReviewStatus.InProgress))
        {
            VisibleManualReviews.Add(item);
        }
    }

    private async Task LoadHistoryAsync()
    {
        RunHistory.Clear();
        foreach (var item in await _historyStore.ListAsync(CancellationToken.None))
        {
            RunHistory.Add(item);
        }
    }

    private static ManualReviewItem NewReview(
        string key,
        string source,
        string title,
        string description,
        bool critical,
        string? targetSql) =>
        new()
        {
            Id = Guid.NewGuid(),
            FindingKey = key,
            Source = source,
            Title = title,
            Description = description,
            Status = ManualReviewStatus.Open,
            TargetSql = targetSql,
            IsCriticalBlocker = critical,
            CreatedAt = DateTimeOffset.UtcNow,
            UpdatedAt = DateTimeOffset.UtcNow
        };
}

public sealed partial class ManualReviewRowViewModel : ObservableObject
{
    [ObservableProperty] private string? _owner;
    [ObservableProperty] private ManualReviewStatus _status;
    [ObservableProperty] private string? _comments;
    [ObservableProperty] private string? _resolution;
    [ObservableProperty] private string? _targetSql;
    [ObservableProperty] private string? _reviewedBy;

    public ManualReviewRowViewModel(ManualReviewItem item)
    {
        Item = item;
        Owner = item.Owner;
        Status = item.Status;
        Comments = item.Comments;
        Resolution = item.Resolution;
        TargetSql = item.TargetSql;
        ReviewedBy = item.ReviewedBy;
    }

    public ManualReviewItem Item { get; }

    public Guid Id => Item.Id;

    public string Title => Item.Title;

    public string Source => Item.Source;

    public string Description => Item.Description;

    public bool IsCriticalBlocker => Item.IsCriticalBlocker;

    public ManualReviewItem ToRecord() =>
        Item with
        {
            Owner = Owner,
            Status = Status,
            Comments = Comments,
            Resolution = Resolution,
            TargetSql = TargetSql,
            ReviewedBy = ReviewedBy,
            ReviewedAt = Status is ManualReviewStatus.Resolved or ManualReviewStatus.AcceptedRisk or
                ManualReviewStatus.NotApplicable
                ? Item.ReviewedAt ?? DateTimeOffset.UtcNow
                : null
        };
}
