using System.IO;
using Microsoft.Data.SqlClient;
using MigrationStudio.Application.DataMigration;
using MigrationStudio.Application.Discovery;
using MigrationStudio.Application.Platform;
using MigrationStudio.Domain.Conversion;
using MigrationStudio.Domain.DataMigration;
using MigrationStudio.Domain.Inventory;
using MigrationStudio.Infrastructure.DataMigration;
using Npgsql;

namespace MigrationStudio.Tests.Integration;

public sealed class DataMigrationIntegrationTests
{
    [DataMigrationIntegrationFact]
    [Trait("Category", "Integration")]
    public async Task MigratesRepresentativeRowsAndPreservesSensitiveHashes()
    {
        var sqlConnectionString =
            Environment.GetEnvironmentVariable("MIGRATIONSTUDIO_SQLSERVER_INTEGRATION")!;
        var postgresConnectionString =
            Environment.GetEnvironmentVariable("MIGRATIONSTUDIO_POSTGRES_INTEGRATION")!;
        var suffix = Guid.NewGuid().ToString("N")[..12];
        var sourceTable = $"MigrationData_{suffix}";
        var targetTable = sourceTable.ToLowerInvariant();
        var binaryHash = Convert.FromHexString("00010203FEFF102030405060708090A0");
        const string passwordHash = "$2a$12$R9h/cIPz0gi.URNNX3kh2OPST9/PgBkqquzi.Ss7KIUgO2t0jWMUW";

        await using var sql = new SqlConnection(sqlConnectionString);
        await using var postgres = new NpgsqlConnection(postgresConnectionString);
        await Task.WhenAll(sql.OpenAsync(), postgres.OpenAsync());
        try
        {
            await ExecuteAsync(
                sql,
                $"""
                 CREATE TABLE [dbo].[{sourceTable}]
                 (
                     [Id] int IDENTITY(10,5) NOT NULL PRIMARY KEY,
                     [UnicodeText] nvarchar(200) NOT NULL,
                     [EmptyText] varchar(20) NOT NULL,
                     [NullableText] varchar(20) NULL,
                     [PasswordHash] varchar(200) NOT NULL,
                     [BinaryHash] varbinary(64) NOT NULL,
                     [Amount] decimal(28,8) NOT NULL,
                     [OccurredAt] datetimeoffset(7) NOT NULL,
                     [ExternalId] uniqueidentifier NOT NULL
                 );
                 SET IDENTITY_INSERT [dbo].[{sourceTable}] ON;
                 INSERT INTO [dbo].[{sourceTable}]
                     ([Id],[UnicodeText],[EmptyText],[NullableText],[PasswordHash],[BinaryHash],[Amount],[OccurredAt],[ExternalId])
                 VALUES
                     (10,N'नमस्ते 你好 🧪','',NULL,'{passwordHash}',0x{Convert.ToHexString(binaryHash).ToLowerInvariant()},
                      12345678901234567890.12345678,'2024-02-29T23:59:59.1234567+05:30',
                      '76543210-abcd-4321-9999-0123456789ab'),
                     (30,N'Καλημέρα','x','','$2id$fixture',0x00FF, -999.00000001,
                      '2000-01-01T00:00:00+00:00','00000000-0000-0000-0000-000000000001');
                 SET IDENTITY_INSERT [dbo].[{sourceTable}] OFF;
                 """);
            await ExecuteAsync(
                postgres,
                $"""
                 CREATE TABLE public."{targetTable}"
                 (
                     "id" integer GENERATED BY DEFAULT AS IDENTITY (START WITH 10 INCREMENT BY 5) PRIMARY KEY,
                     "unicodetext" text NOT NULL,
                     "emptytext" text NOT NULL,
                     "nullabletext" text NULL,
                     "passwordhash" text NOT NULL,
                     "binaryhash" bytea NOT NULL,
                     "amount" numeric(28,8) NOT NULL,
                     "occurredat" timestamp with time zone NOT NULL,
                     "externalid" uuid NOT NULL
                 )
                 """);

            var request = CreateRequest(
                new SqlConnectionStringBuilder(sqlConnectionString),
                postgresConnectionString,
                sourceTable,
                targetTable);
            var root = Path.Combine(Path.GetTempPath(), $"MigrationStudio-{suffix}");
            Directory.CreateDirectory(root);
            try
            {
                var formatter = new CanonicalValueFormatter();
                var classifier = new SensitiveColumnClassifier();
                var planner = new DataMigrationPlanner(classifier);
                using var checkpoints = new JsonMigrationCheckpointStore(new TestPaths(root));
                var engine = new DataMigrationEngine(
                    planner,
                    [
                        new PostgreSqlBinaryCopyStrategy(),
                        new PostgreSqlTextCopyStrategy(formatter),
                        new PostgreSqlBatchInsertStrategy()
                    ],
                    [],
                    checkpoints,
                    new DataMigrationValidator(formatter),
                    new SequenceResetService(),
                    new DataMigrationSession(),
                    new MigrationPauseController(),
                    new TransientErrorClassifier(),
                    formatter);

                var result = await engine.ExecuteAsync(request, null, CancellationToken.None);

                Assert.Equal(MigrationRunState.Completed, result.State);
                Assert.Equal(2, result.Tables.Single().RowsWritten);
                Assert.Equal(ValidationOutcome.Passed, result.Validations.Single().Outcome);
                Assert.True(File.Exists(result.CheckpointPath));
                Assert.Single(result.SequenceResets);

                await using var verify = new NpgsqlCommand(
                    $"""
                     SELECT "passwordhash", "binaryhash", "emptytext", "nullabletext", "unicodetext"
                     FROM public."{targetTable}" WHERE "id" = 10
                     """,
                    postgres);
                await using var reader = await verify.ExecuteReaderAsync();
                Assert.True(await reader.ReadAsync());
                Assert.Equal(passwordHash, reader.GetString(0));
                Assert.Equal(binaryHash, reader.GetFieldValue<byte[]>(1));
                Assert.Equal(string.Empty, reader.GetString(2));
                Assert.True(reader.IsDBNull(3));
                Assert.Equal("नमस्ते 你好 🧪", reader.GetString(4));
            }
            finally
            {
                Directory.Delete(root, true);
            }
        }
        finally
        {
            await ExecuteAsync(postgres, $"DROP TABLE IF EXISTS public.\"{targetTable}\"");
            await ExecuteAsync(sql, $"DROP TABLE IF EXISTS [dbo].[{sourceTable}]");
        }
    }

    private static DataMigrationRequest CreateRequest(
        SqlConnectionStringBuilder source,
        string targetConnectionString,
        string sourceTable,
        string targetTable)
    {
        var tableId = InventoryObjectId.Create(
            source.InitialCatalog,
            InventoryObjectType.Table,
            "dbo",
            sourceTable,
            1);
        var tableObject = new InventoryObject(
            tableId,
            source.InitialCatalog,
            "dbo",
            sourceTable,
            $"[dbo].[{sourceTable}]",
            InventoryObjectType.Table,
            1,
            null,
            null,
            null,
            false,
            true,
            SelectionReason.CompleteDatabase,
            0,
            0,
            [],
            ConversionClassification.Automatic,
            null,
            null,
            "fixture-table-v1",
            [],
            DiscoveryStatus.Discovered);
        var columns = new[]
        {
            Column(tableId, 1, "Id", "int", false, true, 10, 5, 4, 10, 0),
            Column(tableId, 2, "UnicodeText", "nvarchar", false, false, null, null, 400, 0, 0),
            Column(tableId, 3, "EmptyText", "varchar", false, false, null, null, 20, 0, 0),
            Column(tableId, 4, "NullableText", "varchar", true, false, null, null, 20, 0, 0),
            Column(tableId, 5, "PasswordHash", "varchar", false, false, null, null, 200, 0, 0),
            Column(tableId, 6, "BinaryHash", "varbinary", false, false, null, null, 64, 0, 0),
            Column(tableId, 7, "Amount", "decimal", false, false, null, null, 17, 28, 8),
            Column(tableId, 8, "OccurredAt", "datetimeoffset", false, false, null, null, 10, 34, 7),
            Column(tableId, 9, "ExternalId", "uniqueidentifier", false, false, null, null, 16, 0, 0)
        };
        var primaryKey = new ConstraintInventory(
            new InventoryObjectId(Guid.NewGuid()),
            tableId,
            ConstraintKind.PrimaryKey,
            $"PK_{sourceTable}",
            [new ConstraintColumn(1, "Id", false)],
            null,
            [],
            null,
            null,
            null,
            false,
            false,
            false,
            true,
            "PRIMARY",
            0,
            null);
        var inventory = TestInventory.CreateSnapshot([tableObject]) with
        {
            Database = TestInventory.CreateSnapshot([tableObject]).Database with
            {
                DatabaseName = source.InitialCatalog
            },
            Tables =
            [
                new TableInventory(
                    tableId, TableKind.Ordinary, false, null, false, 0, null, false, false,
                    false, false, false, false, false, 2, 0, 0, [])
            ],
            Columns = columns,
            Constraints = [primaryKey]
        };
        var conversion = new ConversionRun(
            Guid.NewGuid(),
            DateTimeOffset.UtcNow,
            source.InitialCatalog,
            new PostgreSqlVersion(18),
            new ConversionOptions(),
            [
                new IdentifierMappingEntry(
                    tableId,
                    "Table",
                    "dbo",
                    sourceTable,
                    $"[dbo].[{sourceTable}]",
                    "public",
                    targetTable,
                    $"public.{targetTable}",
                    sourceTable.Length,
                    targetTable.Length,
                    false,
                    false,
                    null,
                    "fixture")
            ],
            [],
            [],
            [],
            [],
            "integration");
        return new DataMigrationRequest(
            inventory,
            conversion,
            ToOptions(source),
            targetConnectionString,
            new DataMigrationOptions
            {
                ParallelismMode = ParallelismMode.Sequential,
                BatchRowCount = 1,
                CheckpointInterval = 1,
                Validation = new ValidationOptions
                {
                    CompareRowCounts = true,
                    CompareNullCounts = true,
                    ChecksumMode = ChecksumMode.WholeTable
                }
            });
    }

    private static ColumnInventory Column(
        InventoryObjectId tableId,
        int ordinal,
        string name,
        string type,
        bool nullable,
        bool identity,
        decimal? seed,
        decimal? increment,
        short length,
        byte precision,
        byte scale) =>
        new(
            ObjectId: new InventoryObjectId(Guid.NewGuid()),
            ParentObjectId: tableId,
            ColumnId: ordinal,
            OrdinalPosition: ordinal,
            Name: name,
            SystemTypeName: type,
            UserTypeName: type,
            TypeSchema: "sys",
            MaximumLength: length,
            Precision: precision,
            Scale: scale,
            Collation: null,
            IsNullable: nullable,
            IsIdentity: identity,
            IdentitySeed: seed,
            IdentityIncrement: increment,
            IdentityLastValue: null,
            IsIdentityNotForReplication: false,
            IsComputed: false,
            ComputedDefinition: null,
            IsComputedPersisted: false,
            IsComputedDeterministic: null,
            IsSparse: false,
            IsColumnSet: false,
            IsRowGuidColumn: false,
            IsFileStream: false,
            GeneratedAlwaysType: 0,
            IsHidden: false,
            IsMasked: false,
            MaskingFunction: null,
            EncryptionType: null,
            EncryptionAlgorithm: null,
            ColumnEncryptionKey: null,
            XmlSchemaCollection: null,
            DefaultConstraintName: null,
            DefaultDefinition: null,
            RuleName: null,
            ExtendedProperties: []);

    private static SqlServerConnectionOptions ToOptions(SqlConnectionStringBuilder builder) =>
        new()
        {
            Server = builder.DataSource,
            Database = builder.InitialCatalog,
            AuthenticationMode = builder.IntegratedSecurity
                ? SqlServerAuthenticationMode.Windows
                : SqlServerAuthenticationMode.SqlServer,
            Username = builder.IntegratedSecurity ? null : builder.UserID,
            Password = builder.IntegratedSecurity ? null : builder.Password,
            Encrypt = builder.Encrypt,
            TrustServerCertificate = builder.TrustServerCertificate,
            ConnectionTimeoutSeconds = builder.ConnectTimeout,
            CommandTimeoutSeconds = 120
        };

    private static async Task ExecuteAsync(
        System.Data.Common.DbConnection connection,
        string sql)
    {
        await using var command = connection.CreateCommand();
        command.CommandText = sql;
        await command.ExecuteNonQueryAsync();
    }

    private sealed class TestPaths(string root) : IApplicationPaths
    {
        public string ApplicationDataDirectory { get; } = root;

        public string LogsDirectory { get; } = Path.Combine(root, "Logs");

        public string PluginsDirectory { get; } = Path.Combine(root, "Plugins");

        public string SettingsFilePath { get; } = Path.Combine(root, "settings.json");
    }
}

internal sealed class DataMigrationIntegrationFactAttribute : FactAttribute
{
    public DataMigrationIntegrationFactAttribute()
    {
        if (string.IsNullOrWhiteSpace(
                Environment.GetEnvironmentVariable("MIGRATIONSTUDIO_SQLSERVER_INTEGRATION")) ||
            string.IsNullOrWhiteSpace(
                Environment.GetEnvironmentVariable("MIGRATIONSTUDIO_POSTGRES_INTEGRATION")))
        {
            Skip = "Set both database integration connection variables to run end-to-end data migration.";
        }
    }
}
