using Microsoft.Data.SqlClient;
using MigrationStudio.Application.Validation;
using MigrationStudio.Domain.Conversion;
using MigrationStudio.Domain.Inventory;
using MigrationStudio.Domain.Validation;
using MigrationStudio.Validation;
using Npgsql;

namespace MigrationStudio.Tests.Integration;

public sealed class PostMigrationValidationIntegrationTests
{
    [DataMigrationIntegrationFact]
    [Trait("Category", "Integration")]
    public async Task DetectsStructuralDataAndSequenceDefectsWithoutExposingValues()
    {
        var sourceConnectionString =
            Environment.GetEnvironmentVariable("MIGRATIONSTUDIO_SQLSERVER_INTEGRATION")!;
        var targetConnectionString =
            Environment.GetEnvironmentVariable("MIGRATIONSTUDIO_POSTGRES_INTEGRATION")!;
        var suffix = Guid.NewGuid().ToString("N")[..10];
        var sourceName = $"Validation_{suffix}";
        var targetName = sourceName.ToLowerInvariant();
        var primaryKeyName = $"pk_{targetName}";

        await using var source = new SqlConnection(sourceConnectionString);
        await using var target = new NpgsqlConnection(targetConnectionString);
        await Task.WhenAll(source.OpenAsync(), target.OpenAsync());
        try
        {
            await ExecuteAsync(source,
                $"""
                 CREATE TABLE [dbo].[{sourceName}]
                 (
                     [Id] int IDENTITY(1,1) NOT NULL,
                     [SecretToken] nvarchar(max) NOT NULL,
                     CONSTRAINT [PK_{sourceName}] PRIMARY KEY ([Id])
                 );
                 SET IDENTITY_INSERT [dbo].[{sourceName}] ON;
                 INSERT INTO [dbo].[{sourceName}] ([Id],[SecretToken])
                 VALUES (1,N'alpha-secret'),(2,N'beta-secret');
                 SET IDENTITY_INSERT [dbo].[{sourceName}] OFF;
                 """);
            await ExecuteAsync(target,
                $"""
                 CREATE TABLE public."{targetName}"
                 (
                     id integer GENERATED BY DEFAULT AS IDENTITY,
                     secrettoken text NOT NULL,
                     CONSTRAINT "{primaryKeyName}" PRIMARY KEY (id)
                 );
                 INSERT INTO public."{targetName}" (id,secrettoken)
                 OVERRIDING SYSTEM VALUE VALUES (1,'alpha-secret'),(2,'changed-secret');
                 SELECT setval(pg_get_serial_sequence('public."{targetName}"','id'), 1, true);
                 """);

            var request = CreateRequest(
                new SqlConnectionStringBuilder(sourceConnectionString).InitialCatalog,
                sourceName,
                targetName,
                primaryKeyName,
                sourceConnectionString,
                targetConnectionString);
            var engine = new PostMigrationValidationEngine(
                new PostgreSqlValidationMetadataReader(),
                new CanonicalValueSerializer(),
                new CanonicalChecksumService());

            var run = await engine.ValidateAsync(request, null, CancellationToken.None);

            Assert.Contains(run.DataComparisons, item =>
                item.SourceRowCount == item.TargetRowCount &&
                item.Classification == ComparisonClassification.Mismatch);
            Assert.Contains(run.SequenceResults, item => item.WouldGenerateDuplicate);
            Assert.Contains(run.Findings, item =>
                item.RuleId == "SEQUENCE.SEQUENCE_DUPLICATE" &&
                item.Severity == ValidationSeverity.Critical);
            Assert.DoesNotContain("alpha-secret", System.Text.Json.JsonSerializer.Serialize(run),
                StringComparison.Ordinal);
            Assert.Equal(ReadinessStatus.NotReady, run.Readiness.OverallStatus);
        }
        finally
        {
            await ExecuteAsync(target, $"DROP TABLE IF EXISTS public.\"{targetName}\"");
            await ExecuteAsync(source, $"DROP TABLE IF EXISTS [dbo].[{sourceName}]");
        }
    }

    private static ValidationRequest CreateRequest(
        string database,
        string sourceName,
        string targetName,
        string targetPrimaryKey,
        string sourceConnectionString,
        string targetConnectionString)
    {
        var tableId = InventoryObjectId.Create(database, InventoryObjectType.Table, "dbo", sourceName, 1);
        var table = new InventoryObject(
            tableId, database, "dbo", sourceName, $"[dbo].[{sourceName}]",
            InventoryObjectType.Table, 1, null, null, null, false, true,
            SelectionReason.CompleteDatabase, 0, 0, [], ConversionClassification.Automatic,
            null, null, "fixture-table", [], DiscoveryStatus.Discovered);
        var id = Column(tableId, 1, "Id", "int", 4, 10, 0, false, true);
        var secret = Column(tableId, 2, "SecretToken", "nvarchar", -1, 0, 0, false, false);
        var constraint = new ConstraintInventory(
            new InventoryObjectId(Guid.NewGuid()), tableId, ConstraintKind.PrimaryKey,
            $"PK_{sourceName}", [new ConstraintColumn(1, "Id", false)], null, [], null,
            null, null, false, false, false, true, "PRIMARY", 0, null);
        var snapshot = TestInventory.CreateSnapshot([table]) with
        {
            Database = TestInventory.CreateSnapshot([table]).Database with { DatabaseName = database },
            Columns = [id, secret],
            Constraints = [constraint]
        };
        var mappings = new[]
        {
            Mapping(tableId, "Table", "dbo", sourceName, "public", targetName),
            Mapping(tableId, "Column", "dbo", "Id", "public", "id"),
            Mapping(tableId, "Column", "dbo", "SecretToken", "public", "secrettoken"),
            Mapping(tableId, "PrimaryKeyConstraint", "dbo", $"PK_{sourceName}", "public", targetPrimaryKey)
        };
        var conversion = new ConversionRun(
            Guid.NewGuid(), DateTimeOffset.UtcNow, database, new PostgreSqlVersion(18),
            new ConversionOptions(), mappings, [], [], [], [], "integration");
        return new ValidationRequest(
            snapshot,
            conversion,
            new ValidationConnectionOptions(sourceConnectionString, targetConnectionString),
            new ValidationConfiguration
            {
                Level = ValidationLevel.Full,
                Scope = new ValidationScope
                {
                    Schemas = new HashSet<string>(StringComparer.OrdinalIgnoreCase) { "dbo" },
                    Tables = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
                    {
                        $"[dbo].[{sourceName}]"
                    }
                },
                SampleSize = 100
            });
    }

    private static IdentifierMappingEntry Mapping(
        InventoryObjectId owner,
        string type,
        string sourceSchema,
        string sourceName,
        string targetSchema,
        string targetName) =>
        new(owner, type, sourceSchema, sourceName, $"{sourceSchema}.{sourceName}",
            targetSchema, targetName, $"{targetSchema}.{targetName}",
            sourceName.Length, targetName.Length, false, false, null, "integration");

    private static ColumnInventory Column(
        InventoryObjectId table,
        int ordinal,
        string name,
        string type,
        short length,
        byte precision,
        byte scale,
        bool nullable,
        bool identity) =>
        new(
            new InventoryObjectId(Guid.NewGuid()), table, ordinal, ordinal, name, type, type, "sys",
            length, precision, scale, null, nullable, identity, identity ? 1m : null,
            identity ? 1m : null, identity ? 2m : null, false, false, null, false, null,
            false, false, false, false, 0, false, name.Contains("Secret", StringComparison.Ordinal),
            null, null, null, null, null, null, null, null, []);

    private static async Task ExecuteAsync(System.Data.Common.DbConnection connection, string sql)
    {
        await using var command = connection.CreateCommand();
        command.CommandText = sql;
        await command.ExecuteNonQueryAsync();
    }
}
