using System.Text.Json;
using MigrationStudio.Domain.Conversion;
using MigrationStudio.Domain.DataMigration;
using MigrationStudio.Domain.Deployment;
using MigrationStudio.Domain.Inventory;
using MigrationStudio.Domain.Validation;

namespace MigrationStudio.Domain.Reporting;

public enum ManualReviewStatus
{
    Open,
    InProgress,
    Resolved,
    AcceptedRisk,
    NotApplicable
}

public enum RunHistoryKind
{
    Discovery,
    Conversion,
    DataMigration,
    Deployment,
    Validation,
    ReportGeneration
}

public enum RunHistoryStatus
{
    Running,
    Succeeded,
    SucceededWithWarnings,
    Failed,
    Cancelled
}

public enum SourceObjectFinalStatus
{
    ConvertedDeployedValidated,
    ConvertedValidationFailed,
    ManualConversionRequired,
    Unsupported,
    ExcludedExplicitly,
    NotApplicableToPostgreSql,
    Unreconciled
}

public sealed record SourceObjectReconciliation(
    InventoryObjectId SourceObjectId,
    string SourceObject,
    InventoryObjectType ObjectType,
    SourceObjectFinalStatus Status,
    string Reason,
    InventoryObjectId? EffectiveArtifactSourceObjectId);

public sealed record ObjectReconciliationSummary(
    int SelectedSourceObjects,
    int ConvertedDeployedValidated,
    int ConvertedValidationFailed,
    int ManualConversionRequired,
    int Unsupported,
    int ExcludedExplicitly,
    int NotApplicableToPostgreSql,
    int Unreconciled)
{
    public int ReconciledTotal =>
        ConvertedDeployedValidated +
        ConvertedValidationFailed +
        ManualConversionRequired +
        Unsupported +
        ExcludedExplicitly +
        NotApplicableToPostgreSql;

    public bool IsBalanced =>
        Unreconciled == 0 &&
        SelectedSourceObjects == ReconciledTotal;
}

public sealed record ReportTemplate
{
    public string TemplateId { get; init; } = "professional-light";

    public string OrganizationName { get; init; } = string.Empty;

    public string? LogoPath { get; init; }

    public string ProjectName { get; init; } = "SQL Server to PostgreSQL Migration";

    public string ReportTitle { get; init; } = "Migration Executive Summary";

    public string PreparedBy { get; init; } = string.Empty;

    public string ReviewedBy { get; init; } = string.Empty;

    public string ClassificationMarking { get; init; } = "Internal";

    public string Footer { get; init; } = "Generated by SQL Server to PostgreSQL Migration Studio";

    public string DateTimeFormat { get; init; } = "yyyy-MM-dd HH:mm:ss zzz";

    public bool UseDarkDashboardTheme { get; init; }
}

public sealed record MigrationEndpointSummary(
    string Server,
    string Database,
    string Version,
    string Edition);

public sealed record MigrationReportRequest
{
    public required InventorySnapshot Inventory { get; init; }

    public ConversionRun? Conversion { get; init; }

    public DataMigrationResult? DataMigration { get; init; }

    public DeploymentResult? Deployment { get; init; }

    public ValidationRun? Validation { get; init; }

    public required MigrationEndpointSummary Source { get; init; }

    public required MigrationEndpointSummary Target { get; init; }

    public ReportTemplate Template { get; init; } = new();

    public IReadOnlyList<ManualReviewItem> ManualReviews { get; init; } = [];

    public string ApplicationVersion { get; init; } = string.Empty;
}

public sealed record MigrationReportSummary(
    Guid ReportRunId,
    DateTimeOffset GeneratedAt,
    string ApplicationVersion,
    MigrationEndpointSummary Source,
    MigrationEndpointSummary Target,
    MigrationScopeMode Scope,
    IReadOnlyList<string> IncludedSchemas,
    int IncludedObjects,
    int ExcludedObjects,
    string SchemaConversionResult,
    string DataMigrationResult,
    string DeploymentResult,
    string ValidationResult,
    string OverallReadiness,
    int CriticalBlockers,
    int Warnings,
    int ManualReviews,
    int Unsupported,
    long RowsRead,
    long RowsWritten,
    long FailedRows,
    TimeSpan TotalDuration,
    double RowsPerSecond,
    TimeSpan DeploymentDuration,
    TimeSpan ValidationDuration)
{
    public bool RowsReconcile => RowsRead == RowsWritten + FailedRows;

    public long UnreconciledRows => RowsRead - RowsWritten - FailedRows;
}

public sealed record MigrationReportDocument
{
    public const int CurrentSchemaVersion = 2;

    public int ReportSchemaVersion { get; init; } = CurrentSchemaVersion;

    public required MigrationReportSummary Summary { get; init; }

    public required InventorySnapshot Inventory { get; init; }

    public ConversionRun? Conversion { get; init; }

    public DataMigrationResult? DataMigration { get; init; }

    public DeploymentResult? Deployment { get; init; }

    public ValidationRun? Validation { get; init; }

    public IReadOnlyList<ManualReviewItem> ManualReviews { get; init; } = [];

    public ReportTemplate Template { get; init; } = new();

    public IReadOnlyList<SourceObjectReconciliation> ObjectReconciliation { get; init; } = [];

    public ObjectReconciliationSummary ReconciliationSummary { get; init; } =
        new(0, 0, 0, 0, 0, 0, 0, 0);
}

public sealed record ReportPackageResult(
    Guid ReportRunId,
    string ReportsDirectory,
    IReadOnlyList<string> Files,
    DateTimeOffset StartedAt,
    DateTimeOffset CompletedAt);

public sealed record ManualReviewItem
{
    public required Guid Id { get; init; }

    public required string FindingKey { get; init; }

    public required string Source { get; init; }

    public required string Title { get; init; }

    public string Description { get; init; } = string.Empty;

    public string? Owner { get; init; }

    public ManualReviewStatus Status { get; init; } = ManualReviewStatus.Open;

    public string? Comments { get; init; }

    public string? Resolution { get; init; }

    public string? TargetSql { get; init; }

    public DateTimeOffset CreatedAt { get; init; }

    public DateTimeOffset UpdatedAt { get; init; }

    public DateTimeOffset? ReviewedAt { get; init; }

    public string? ReviewedBy { get; init; }

    public bool IsCriticalBlocker { get; init; }
}

public sealed record RunHistoryEntry(
    Guid RunId,
    RunHistoryKind Kind,
    RunHistoryStatus Status,
    DateTimeOffset StartedAt,
    DateTimeOffset? CompletedAt,
    string SourceDatabase,
    string? TargetDatabase,
    string Summary,
    string PayloadFile,
    string? ParentRunId = null);

public sealed record RunHistoryRecord(
    RunHistoryEntry Entry,
    JsonElement Payload);
