using System.IO;
using ClosedXML.Excel;
using ClosedXML.Graphics;
using Microsoft.Extensions.Logging.Abstractions;
using MigrationStudio.Application.Conversion;
using MigrationStudio.Deployment;
using MigrationStudio.Domain.Conversion;
using MigrationStudio.Domain.Inventory;
using MigrationStudio.Infrastructure.Conversion;
using MigrationStudio.Infrastructure.Conversion.Converters;
using MigrationStudio.Reporting;
using MigrationStudio.Validation;

namespace MigrationStudio.Tests.Conversion;

public sealed class ConversionEngineTests
{
    [Fact]
    public async Task Engine_ConvertsEveryIncludedObject_AndIsDeterministic()
    {
        var inventory = CreateInventory();
        var engine = CreateEngine();

        var first = await engine.ConvertAsync(inventory, new ConversionOptions(), null, CancellationToken.None);
        var second = await engine.ConvertAsync(inventory, new ConversionOptions(), null, CancellationToken.None);

        foreach (var source in inventory.Objects.Where(item => item.IsIncluded))
        {
            Assert.Contains(first.Artifacts, item => item.SourceObjectId == source.Id);
        }
        Assert.Equal(
            first.Artifacts.Select(item => item.ContentHash),
            second.Artifacts.Select(item => item.ContentHash));
        Assert.Equal(first.RunId, second.RunId);
        Assert.Contains(first.Artifacts, item =>
            item.DeploymentPhase == DeploymentPhase.Tables &&
            item.PostgreSqlDefinition.Contains("GENERATED BY DEFAULT AS IDENTITY", StringComparison.Ordinal));
        Assert.Contains(first.Artifacts, item =>
            item.DeploymentPhase == DeploymentPhase.Views &&
            item.PostgreSqlDefinition.Contains("LIMIT 5", StringComparison.Ordinal));
        Assert.Contains(first.Artifacts, item =>
            item.DeploymentPhase == DeploymentPhase.PrimaryKeys &&
            item.PostgreSqlDefinition.Contains("PRIMARY KEY", StringComparison.Ordinal));
        Assert.Contains(first.Artifacts, item =>
            item.DeploymentPhase == DeploymentPhase.Indexes &&
            item.PostgreSqlDefinition.Contains("INCLUDE", StringComparison.Ordinal));
        Assert.Contains(first.Artifacts, item =>
            item.DeploymentPhase == DeploymentPhase.Sequences &&
            item.PostgreSqlDefinition.Contains("CACHE 50", StringComparison.Ordinal));
        Assert.Contains(first.Artifacts, item =>
            item.Classification == ConversionClassification.ManualConversion &&
            item.TargetObjectId.ObjectType == InventoryObjectType.Synonym.ToString());
        var triggerMapping = Assert.Single(first.IdentifierMappings, item =>
            item.SourceName == "TRG_DigiPay_TrainerDetailsHistory_Del");
        Assert.True(triggerMapping.AutoRecovered);
        Assert.NotNull(triggerMapping.SourceKey.TriggerKey);
        Assert.Equal(0, first.MappingSet.UnresolvedRequiredCount);
        Assert.All(first.MappingSet.Coverage, item =>
            Assert.Equal(item.IncludedCount, item.MappedCount));
    }

    [Fact]
    public async Task Engine_DoesNotCompleteWhenAnIncludedColumnMappingIsMissing()
    {
        var inventory = CreateInventory();
        var missingColumn = inventory.Columns[1];
        var engine = CreateEngine(new IncompleteIdentifierMappingService(
            missingColumn.ObjectId));

        var exception = await Assert.ThrowsAsync<InvalidOperationException>(() =>
            engine.ConvertAsync(
                inventory,
                new ConversionOptions(),
                null,
                CancellationToken.None));

        Assert.Contains("identifier mapping is incomplete", exception.Message, StringComparison.OrdinalIgnoreCase);
        Assert.Contains(missingColumn.Name, exception.Message, StringComparison.Ordinal);
    }

    [Fact]
    public async Task Engine_DoesNotBeginConversionWhenIncludedTriggerMappingIsMissing()
    {
        var inventory = CreateInventory();
        var trigger = Assert.Single(
            inventory.Objects,
            item => item.ObjectType == InventoryObjectType.Trigger);
        var engine = CreateEngine(new IncompleteIdentifierMappingService(trigger.Id));

        var exception = await Assert.ThrowsAsync<InvalidOperationException>(() =>
            engine.ConvertAsync(
                inventory,
                new ConversionOptions(),
                null,
                CancellationToken.None));

        Assert.Contains("identifier mapping is incomplete", exception.Message, StringComparison.OrdinalIgnoreCase);
        Assert.Contains(trigger.SourceName, exception.Message, StringComparison.Ordinal);
    }

    [Theory]
    [InlineData(IdentityConversionStrategy.GeneratedAlwaysAsIdentity, "GENERATED ALWAYS AS IDENTITY")]
    [InlineData(IdentityConversionStrategy.SequenceAndDefault, "DEFAULT nextval")]
    public async Task Engine_AppliesConfiguredIdentityStrategy(
        IdentityConversionStrategy strategy,
        string expected)
    {
        var run = await CreateEngine().ConvertAsync(
            CreateInventory(),
            new ConversionOptions { IdentityStrategy = strategy },
            null,
            CancellationToken.None);

        Assert.Contains(
            run.Artifacts,
            item => item.DeploymentPhase == DeploymentPhase.Tables &&
                    item.PostgreSqlDefinition.Contains(expected, StringComparison.Ordinal));
    }

    [Fact]
    public async Task Engine_TranslatesUtcDefaultAndUsesMappedConstraintAndIndexIdentifiers()
    {
        var inventory = CreateInventory();
        var table = inventory.Objects.Single(item => item.ObjectType == InventoryObjectType.Table);
        var check = Object(
            InventoryObjectType.CheckConstraint,
            table.SourceSchema,
            "CK_Customer_Name",
            99,
            table.Id);
        var nameColumn = inventory.Columns.Single(item => item.Name == "Name");
        inventory = inventory with
        {
            Objects = inventory.Objects.Append(check).ToArray(),
            Columns = inventory.Columns.Select(item =>
                item.ObjectId == nameColumn.ObjectId
                    ? item with { DefaultDefinition = "SYSUTCDATETIME()" }
                    : item).ToArray(),
            Constraints = inventory.Constraints.Append(
                new ConstraintInventory(
                    check.Id,
                    table.Id,
                    ConstraintKind.Check,
                    check.SourceName,
                    [],
                    null,
                    [],
                    "([Name] <> N'')",
                    null,
                    null,
                    false,
                    false,
                    false,
                    false,
                    null,
                    0,
                    null)).ToArray()
        };

        var run = await CreateEngine().ConvertAsync(
            inventory,
            new ConversionOptions(),
            null,
            CancellationToken.None);
        var primaryKey = inventory.Objects.Single(item => item.ObjectType == InventoryObjectType.PrimaryKey);
        var index = inventory.Objects.Single(item => item.ObjectType == InventoryObjectType.Index);
        var mappedTable = run.IdentifierMappings.Single(item => item.SourceObjectId == table.Id);
        var mappedPrimaryKey = run.IdentifierMappings.Single(item => item.SourceObjectId == primaryKey.Id);
        var mappedIndex = run.IdentifierMappings.Single(item => item.SourceObjectId == index.Id);
        var mappedCustomerId = run.IdentifierMappings.Single(item =>
            item.ObjectType.Equals("column", StringComparison.OrdinalIgnoreCase) &&
            item.SourceName == "CustomerId");
        var mappedName = run.IdentifierMappings.Single(item =>
            item.ObjectType.Equals("column", StringComparison.OrdinalIgnoreCase) &&
            item.SourceName == "Name");
        var tableSql = run.Artifacts.Single(item => item.SourceObjectId == table.Id).PostgreSqlDefinition;
        var primaryKeySql = run.Artifacts.Single(item => item.SourceObjectId == primaryKey.Id).PostgreSqlDefinition;
        var indexSql = run.Artifacts.Single(item => item.SourceObjectId == index.Id).PostgreSqlDefinition;
        var checkSql = run.Artifacts.Single(item => item.SourceObjectId == check.Id).PostgreSqlDefinition;

        Assert.Contains("timezone('UTC', CURRENT_TIMESTAMP)", tableSql, StringComparison.Ordinal);
        Assert.DoesNotContain("SYSUTCDATETIME", tableSql, StringComparison.OrdinalIgnoreCase);
        Assert.Contains(mappedTable.TargetName, primaryKeySql, StringComparison.Ordinal);
        Assert.Contains(mappedPrimaryKey.TargetName, primaryKeySql, StringComparison.Ordinal);
        Assert.Contains(mappedCustomerId.TargetName, primaryKeySql, StringComparison.Ordinal);
        Assert.Contains(mappedTable.TargetName, indexSql, StringComparison.Ordinal);
        Assert.Contains(mappedIndex.TargetName, indexSql, StringComparison.Ordinal);
        Assert.Contains(mappedName.TargetName, indexSql, StringComparison.Ordinal);
        Assert.Contains(mappedName.TargetName, checkSql, StringComparison.Ordinal);
        Assert.DoesNotContain("[Name]", checkSql, StringComparison.Ordinal);
    }

    [Fact]
    public async Task Engine_ConvertsCertStateTemporalDefaultAndDependentCheckConstraint()
    {
        var schema = Object(InventoryObjectType.Schema, string.Empty, "cert", 201, null);
        var table = Object(InventoryObjectType.Table, "cert", "state", 202, null);
        var check = Object(
            InventoryObjectType.CheckConstraint,
            "cert",
            "ck_state_dates",
            203,
            table.Id);
        var inventory = TestInventory.CreateSnapshot([schema, table, check]) with
        {
            Schemas = [new SchemaInventory(schema, "dbo", 2, false, true)],
            Tables =
            [
                new TableInventory(
                    table.Id, TableKind.Ordinary, false, null, false, 0, null, false, false, false,
                    false, false, false, false, 0, 0, 0, [])
            ],
            Columns =
            [
                Column(table, 1, "state_id", "int", false, false, null, null, null),
                Column(
                    table,
                    2,
                    "effective_from",
                    "datetime2",
                    false,
                    false,
                    "SYSUTCDATETIME()",
                    null,
                    null,
                    8),
                Column(
                    table,
                    3,
                    "effective_to",
                    "datetime2",
                    true,
                    false,
                    null,
                    null,
                    null,
                    8)
            ],
            Constraints =
            [
                new ConstraintInventory(
                    check.Id,
                    table.Id,
                    ConstraintKind.Check,
                    check.SourceName,
                    [],
                    null,
                    [],
                    "([effective_from] <= sysutcdatetime() AND " +
                    "([effective_to] IS NULL OR [effective_to] >= GETUTCDATE()))",
                    null,
                    null,
                    false,
                    false,
                    false,
                    false,
                    null,
                    0,
                    null)
            ],
            Dependencies =
            [
                new InventoryDependency(
                    check.Id,
                    table.Id,
                    DependencyKind.SqlExpression,
                    table.QualifiedSourceName,
                    true,
                    false)
            ]
        };

        var run = await CreateEngine().ConvertAsync(
            inventory,
            new ConversionOptions(),
            null,
            CancellationToken.None);
        var stateArtifact = Assert.Single(run.Artifacts, item =>
            item.SourceObjectId == table.Id);
        var checkArtifact = Assert.Single(run.Artifacts, item =>
            item.SourceObjectId == check.Id);

        Assert.Equal("cert.state", stateArtifact.TargetObjectId.QualifiedName);
        Assert.Contains(
            "DEFAULT timezone('UTC', CURRENT_TIMESTAMP)",
            stateArtifact.PostgreSqlDefinition,
            StringComparison.Ordinal);
        Assert.DoesNotContain(
            "sysutcdatetime",
            stateArtifact.PostgreSqlDefinition,
            StringComparison.OrdinalIgnoreCase);
        Assert.Equal("cert.ck_state_dates", checkArtifact.TargetObjectId.QualifiedName);
        Assert.Contains(
            "timezone('UTC', CURRENT_TIMESTAMP)",
            checkArtifact.PostgreSqlDefinition,
            StringComparison.Ordinal);
        Assert.DoesNotContain(
            "sysutcdatetime",
            checkArtifact.PostgreSqlDefinition,
            StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain(
            "getutcdate",
            checkArtifact.PostgreSqlDefinition,
            StringComparison.OrdinalIgnoreCase);
        Assert.Contains(table.Id, checkArtifact.Dependencies);
    }

    [Fact]
    public async Task Engine_DoesNotEmitCreateIndexWithEmptyKeyList()
    {
        var inventory = CreateInventory();
        inventory = inventory with
        {
            Indexes = inventory.Indexes.Select(item => item with { Columns = [] }).ToArray()
        };

        var run = await CreateEngine().ConvertAsync(
            inventory,
            new ConversionOptions(),
            null,
            CancellationToken.None);
        var sourceIndex = inventory.Objects.Single(item =>
            item.ObjectType == InventoryObjectType.Index);
        var artifact = run.Artifacts.Single(item => item.SourceObjectId == sourceIndex.Id);

        Assert.Equal(ConversionClassification.ManualConversion, artifact.Classification);
        Assert.True(artifact.RequiresManualReview);
        Assert.Contains("no key columns", artifact.PostgreSqlDefinition, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("()", artifact.PostgreSqlDefinition, StringComparison.Ordinal);
    }

    [Fact]
    public async Task Engine_UsesMappedLowercaseSchemaAcrossExecutableArtifacts()
    {
        const string sourceSchema = "NREGA_SK";
        var inventory = CreateInventory();
        var remappedObjects = inventory.Objects.Select(item =>
            item.ObjectType == InventoryObjectType.Schema
                ? item with
                {
                    SourceName = sourceSchema,
                    QualifiedSourceName = $"[{sourceSchema}]"
                }
                : item with
                {
                    SourceSchema = sourceSchema,
                    QualifiedSourceName = $"[{sourceSchema}].[{item.SourceName}]",
                    SourceDefinition = item.SourceDefinition?
                        .Replace("[dbo]", $"[{sourceSchema}]", StringComparison.OrdinalIgnoreCase)
                }).ToList();
        var table = remappedObjects.Single(item => item.ObjectType == InventoryObjectType.Table);
        var function = Object(
            InventoryObjectType.Function,
            sourceSchema,
            "FnChkSau_DupAcc",
            100,
            null,
            $"CREATE FUNCTION [{sourceSchema}].[FnChkSau_DupAcc](@value nvarchar(100)) RETURNS bit AS BEGIN RETURN 0; END");
        var procedure = Object(
            InventoryObjectType.StoredProcedure,
            sourceSchema,
            "UpdateCustomer",
            101,
            null,
            $"CREATE PROCEDURE [{sourceSchema}].[UpdateCustomer] AS BEGIN UPDATE [{sourceSchema}].[Customer] SET [Name] = [Name]; END");
        var check = Object(
            InventoryObjectType.CheckConstraint,
            sourceSchema,
            "ChkSAU_DupAcc",
            102,
            table.Id);
        var unique = Object(
            InventoryObjectType.UniqueConstraint,
            sourceSchema,
            "UQ_Customer_Name",
            103,
            table.Id);
        var foreignKey = Object(
            InventoryObjectType.ForeignKey,
            sourceSchema,
            "FK_Customer_Parent",
            104,
            table.Id);
        remappedObjects.AddRange([function, procedure, check, unique, foreignKey]);

        var schema = remappedObjects.Single(item => item.ObjectType == InventoryObjectType.Schema);
        inventory = inventory with
        {
            Objects = remappedObjects,
            Schemas = [new SchemaInventory(schema, "dbo", remappedObjects.Count - 1, false, true)],
            Constraints = inventory.Constraints.Concat(
            [
                new ConstraintInventory(
                    check.Id, table.Id, ConstraintKind.Check, check.SourceName, [], null, [],
                    $"([{sourceSchema}].[FnChkSau_DupAcc]([Name])=(0))",
                    null, null, false, false, false, false, null, 0, null),
                new ConstraintInventory(
                    unique.Id, table.Id, ConstraintKind.Unique, unique.SourceName,
                    [new ConstraintColumn(1, "Name", false)], null, [], null,
                    null, null, false, false, false, false, null, 0, null),
                new ConstraintInventory(
                    foreignKey.Id, table.Id, ConstraintKind.ForeignKey, foreignKey.SourceName,
                    [new ConstraintColumn(1, "CustomerId", false)], table.Id,
                    [new ConstraintColumn(1, "CustomerId", false)], null,
                    "NO ACTION", "NO ACTION", false, false, false, false, null, 0, null)
            ]).ToArray(),
            Modules = inventory.Modules.Concat(
            [
                new ModuleInventory(
                    function.Id, ModuleKind.ScalarFunction, true, true, false, false, false, false,
                    null, false, false, false, false,
                    [
                        new ModuleParameterInventory(
                            0, string.Empty, "sys", "bit", 1, 1, 0, false, false, null, false, false),
                        new ModuleParameterInventory(
                            1, "@value", "sys", "nvarchar", 200, 0, 0, false, false, null, false, false)
                    ],
                    []),
                new ModuleInventory(
                    procedure.Id, ModuleKind.StoredProcedure, true, true, false, false, false, false,
                    null, false, false, false, false, [], [])
            ]).ToArray(),
            Dependencies = inventory.Dependencies.Concat(
            [
                new InventoryDependency(
                    function.Id,
                    table.Id,
                    DependencyKind.SqlExpression,
                    table.QualifiedSourceName,
                    true,
                    false),
                new InventoryDependency(
                    check.Id,
                    function.Id,
                    DependencyKind.SqlExpression,
                    function.QualifiedSourceName,
                    true,
                    false)
            ]).ToArray()
        };

        var run = await CreateEngine().ConvertAsync(
            inventory,
            new ConversionOptions(),
            null,
            CancellationToken.None);

        var executableSql = run.Artifacts
            .Where(item => !string.IsNullOrWhiteSpace(item.PostgreSqlDefinition))
            .Select(item => item.PostgreSqlDefinition)
            .ToArray();
        Assert.All(executableSql, sql =>
            Assert.DoesNotContain("\"NREGA_SK\"", sql, StringComparison.Ordinal));
        Assert.Contains(run.Artifacts, item =>
            item.SourceObjectId == schema.Id &&
            item.PostgreSqlDefinition.Contains("CREATE SCHEMA IF NOT EXISTS nrega_sk", StringComparison.Ordinal));
        Assert.Contains(run.Artifacts, item =>
            item.SourceObjectId == table.Id &&
            item.PostgreSqlDefinition.Contains("CREATE TABLE nrega_sk.customer", StringComparison.Ordinal));
        Assert.Contains(run.Artifacts, item =>
    item.SourceObjectId == check.Id &&
    item.PostgreSqlDefinition.Contains(
        "NOT (nrega_sk.fnchksau_dupacc(name))",
        StringComparison.Ordinal));
        Assert.Contains(run.Artifacts, item =>
            item.SourceObjectId == unique.Id &&
            item.PostgreSqlDefinition.Contains("ALTER TABLE nrega_sk.customer", StringComparison.Ordinal));
        Assert.Contains(run.Artifacts, item =>
            item.SourceObjectId == foreignKey.Id &&
            item.PostgreSqlDefinition.Contains("REFERENCES nrega_sk.customer", StringComparison.Ordinal));
        Assert.Contains(run.Artifacts, item =>
            item.DeploymentPhase == DeploymentPhase.Indexes &&
            item.PostgreSqlDefinition.Contains(" ON nrega_sk.customer ", StringComparison.Ordinal));
        Assert.Contains(run.Artifacts, item =>
            item.SourceObjectId == function.Id &&
            item.PostgreSqlDefinition.Contains(
                "FUNCTION nrega_sk.fnchksau_dupacc",
                StringComparison.Ordinal));
        var functionArtifact = Assert.Single(run.Artifacts, item =>
            item.SourceObjectId == function.Id);
        var checkArtifact = Assert.Single(run.Artifacts, item =>
            item.SourceObjectId == check.Id);
        Assert.Equal(DeploymentPhase.PreDataFunctions, functionArtifact.DeploymentPhase);
        Assert.Equal("06_PreDataFunctions.sql", functionArtifact.ScriptFileName);
        Assert.Contains(function.Id, checkArtifact.Dependencies);
        var orderedArtifacts = run.Artifacts.ToList();
        Assert.True(
            orderedArtifacts.IndexOf(functionArtifact) <
            orderedArtifacts.IndexOf(checkArtifact));
        Assert.Contains(run.Artifacts, item =>
            item.SourceObjectId == procedure.Id &&
            item.PostgreSqlDefinition.Contains(
                "PROCEDURE nrega_sk.updatecustomer",
                StringComparison.Ordinal));
        Assert.Contains(run.Artifacts, item =>
            item.DeploymentPhase is DeploymentPhase.Views or DeploymentPhase.Triggers &&
            item.PostgreSqlDefinition.Contains("nrega_sk.", StringComparison.Ordinal));
        Assert.Contains(run.Artifacts, item =>
            item.DeploymentPhase == DeploymentPhase.Sequences &&
            item.PostgreSqlDefinition.Contains("nrega_sk.", StringComparison.Ordinal));
        Assert.All(run.Artifacts, artifact =>
            Assert.Equal(
                "nrega_sk",
                artifact.TargetObjectId.Schema));
    }

    [Fact]
    public async Task DocumentStore_TableIsExecutableAndPrecedesItsPrimaryKey()
    {
        var schema = Object(InventoryObjectType.Schema, string.Empty, "cert", 200, null);
        var table = Object(InventoryObjectType.Table, "cert", "DocumentStore", 201, null);
        var primaryKey = Object(
            InventoryObjectType.PrimaryKey,
            "cert",
            "PK_DocumentStore",
            202,
            table.Id);
        var inventory = TestInventory.CreateSnapshot([schema, table, primaryKey]) with
        {
            Schemas = [new SchemaInventory(schema, "dbo", 2, false, true)],
            Tables =
            [
                new TableInventory(
                    table.Id, TableKind.Ordinary, false, null, false, 0, null, false, false,
                    false, false, false, false, false, 0, 0, 0, [])
            ],
            Columns =
            [
                Column(
                    table, 1, "DocumentId", "uniqueidentifier", false, false,
                    "(newsequentialid())", null, null, 16),
                Column(
                    table, 2, "UploadedAt", "datetime2", false, false,
                    "((sysutcdatetime()))", null, null, 8)
            ],
            Constraints =
            [
                new ConstraintInventory(
                    primaryKey.Id,
                    table.Id,
                    ConstraintKind.PrimaryKey,
                    "PK_DocumentStore",
                    [new ConstraintColumn(1, "DocumentId", false)],
                    null,
                    [],
                    null,
                    null,
                    null,
                    false,
                    false,
                    false,
                    true,
                    "PRIMARY",
                    0,
                    null)
            ],
            Dependencies = []
        };

        var run = await CreateEngine().ConvertAsync(
            inventory,
            new ConversionOptions
            {
                EnablePgCrypto = true,
                UseRandomUuidForNewSequentialId = true
            },
            null,
            CancellationToken.None);

        var tableArtifact = Assert.Single(run.Artifacts, item => item.SourceObjectId == table.Id);
        var primaryKeyArtifact = Assert.Single(run.Artifacts, item => item.SourceObjectId == primaryKey.Id);
        Assert.False(tableArtifact.RequiresManualReview);
        Assert.True(tableArtifact.Validation.IsStructurallyValid, tableArtifact.Validation.Message);
        Assert.Contains("DEFAULT gen_random_uuid()", tableArtifact.PostgreSqlDefinition, StringComparison.Ordinal);
        Assert.Contains(
            "DEFAULT timezone('UTC', CURRENT_TIMESTAMP)",
            tableArtifact.PostgreSqlDefinition,
            StringComparison.Ordinal);
        Assert.Contains(table.Id, primaryKeyArtifact.Dependencies);
        var ordered = run.Artifacts.ToList();
        Assert.True(ordered.IndexOf(tableArtifact) < ordered.IndexOf(primaryKeyArtifact));
    }

    [Fact]
    public async Task PackageWriter_EmitsManifestScriptsManualReviewAndExcelHtmlReports()
    {
        var run = await CreateEngine().ConvertAsync(
            CreateInventory(),
            new ConversionOptions(),
            null,
            CancellationToken.None);
        var parent = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString("N"));
        try
        {
            var package = await new MigrationPackageWriter(new ConversionReportWriter())
                .WriteAsync(run, parent, CancellationToken.None);

            Assert.True(File.Exists(Path.Combine(package, "manifest.json")));
            Assert.True(File.Exists(Path.Combine(package, "05_Tables.sql")));
            Assert.True(File.Exists(Path.Combine(package, "10_Sequences.sql")));
            Assert.True(File.Exists(Path.Combine(package, "16_Views.sql")));
            Assert.True(File.Exists(Path.Combine(package, "Reports", "Conversion_Report.xlsx")));
            Assert.True(File.Exists(Path.Combine(package, "Reports", "Conversion_Report.html")));
            Assert.True(File.Exists(Path.Combine(package, "Reports", "Identifier_Mapping.csv")));
            Assert.NotEmpty(Directory.GetFiles(Path.Combine(package, "ManualReview"), "*.sql"));
        }
        finally
        {
            if (Directory.Exists(parent))
            {
                Directory.Delete(parent, recursive: true);
            }
        }
    }

    [Fact]
    public async Task IdentifierReport_UsesTextAndAccessibleGreenYellowAmberRedStatuses()
    {
        var run = await CreateEngine().ConvertAsync(
            CreateInventory(),
            new ConversionOptions(),
            null,
            CancellationToken.None);
        var template = run.IdentifierMappings[0];
        var mappings = new[]
        {
            template with
            {
                MappingStatus = IdentifierMappingStatus.Safe,
                Severity = IdentifierMappingSeverity.Information
            },
            template with
            {
                SourceName = "user",
                TargetName = "\"user\"",
                IsReservedWord = true,
                RequiresQuoting = true,
                WasQuoted = true,
                MappingStatus = IdentifierMappingStatus.ReservedWordSafelyQuoted
            },
            template with
            {
                SourceName = new string('x', 70),
                WasShortened = true,
                MappingStatus = IdentifierMappingStatus.AutomaticallyShortened,
                Severity = IdentifierMappingSeverity.Warning,
                AutoRecovered = true,
                MappingAction = IdentifierMappingAction.AutoRecovered
            },
            template with
            {
                SourceName = "blocking",
                MappingStatus = IdentifierMappingStatus.BlockingConflict,
                Severity = IdentifierMappingSeverity.Error,
                ManualReviewRequired = true
            }
        };
        run = run with { IdentifierMappings = mappings };
        var directory = Path.Combine(Path.GetTempPath(), Guid.NewGuid().ToString("N"));
        try
        {
            await new ConversionReportWriter().WriteAsync(run, directory, CancellationToken.None);
            using var font = File.OpenRead(@"C:\Windows\Fonts\arial.ttf");
            var graphics = DefaultGraphicEngine.CreateOnlyWithFonts(font);
            using var workbook = new XLWorkbook(
                Path.Combine(directory, "Identifier_Mapping.xlsx"),
                new LoadOptions { GraphicEngine = graphics });
            var sheet = workbook.Worksheet("Identifier Mapping");
            Assert.Equal("Mapping status", sheet.Cell(1, 21).GetString());
            Assert.Equal("Mapping action", sheet.Cell(1, 28).GetString());
            Assert.Equal("Auto-recovered", sheet.Cell(1, 30).GetString());
            Assert.True(sheet.Cell(4, 30).GetBoolean());
            Assert.Equal("Safe", sheet.Cell(2, 21).GetString());
            Assert.Equal("Reserved word — safely quoted", sheet.Cell(3, 21).GetString());
            Assert.Equal("Long identifier — automatically shortened", sheet.Cell(4, 21).GetString());
            Assert.Equal("Blocking identifier conflict", sheet.Cell(5, 21).GetString());
            Assert.Equal(XLColor.FromHtml("#D9EAD3"), sheet.Cell(2, 1).Style.Fill.BackgroundColor);
            Assert.Equal(XLColor.FromHtml("#FFF2CC"), sheet.Cell(3, 1).Style.Fill.BackgroundColor);
            Assert.Equal(XLColor.FromHtml("#F4B183"), sheet.Cell(4, 1).Style.Fill.BackgroundColor);
            Assert.Equal(XLColor.FromHtml("#C00000"), sheet.Cell(5, 1).Style.Fill.BackgroundColor);
            Assert.Contains("Identifier status legend", sheet.CellsUsed().Select(cell => cell.GetString()));
            Assert.True(sheet.AutoFilter.IsEnabled);
            Assert.True(sheet.SheetView.SplitRow >= 1);

            var html = await File.ReadAllTextAsync(Path.Combine(directory, "Conversion_Report.html"));
            Assert.Contains("\"css\":\"reserved\"", html, StringComparison.Ordinal);
            Assert.Contains("\"css\":\"transformed\"", html, StringComparison.Ordinal);
            Assert.Contains("\"css\":\"blocking\"", html, StringComparison.Ordinal);
            Assert.Contains("data-filter=\"reserved\"", html, StringComparison.Ordinal);
            Assert.Contains("data-filter=\"autoRecovered\"", html, StringComparison.Ordinal);
            Assert.Contains("id=\"identifier-type\"", html, StringComparison.Ordinal);
            Assert.Contains("\"action\":\"AutoRecovered\"", html, StringComparison.Ordinal);
            Assert.Contains("page=0,size=100", html, StringComparison.Ordinal);
        }
        finally
        {
            if (Directory.Exists(directory))
            {
                Directory.Delete(directory, recursive: true);
            }
        }
    }

    private static ConversionEngine CreateEngine(
        IIdentifierMappingService? identifierMappingService = null)
    {
        var identifiers = identifierMappingService ??
            new PostgreSqlIdentifierMappingService();
        var types = new PostgreSqlTypeMappingRegistry();
        var expressions = new StructuredSqlExpressionTranslator();
        IObjectConverter<InventoryObject, string>[] converters =
        [
            new SchemaConverter(),
            new TableConverter(),
            new ConstraintConverter(),
            new IndexConverter(),
            new SequenceConverter(),
            new UserDefinedTypeConverter(),
            new ProgrammableObjectConverter(),
            new SecurityConverter(),
            new SynonymConverter(),
            new FallbackObjectConverter()
        ];
        return new ConversionEngine(
            converters,
            identifiers,
            types,
            expressions,
            new GeneratedSqlValidator(),
            NullLogger<ConversionEngine>.Instance);
    }

    private sealed class IncompleteIdentifierMappingService(
        InventoryObjectId missingObjectId) : IIdentifierMappingService
    {
        public IIdentifierMapper CreateMapper(
            InventorySnapshot inventory,
            ConversionOptions options) =>
            new IncompleteIdentifierMapper(
                new PostgreSqlIdentifierMappingService().CreateMapper(
                    inventory,
                    options),
                missingObjectId);
    }

    private sealed class IncompleteIdentifierMapper(
        IIdentifierMapper inner,
        InventoryObjectId missingObjectId) : IIdentifierMapper
    {
        public string MapSchema(string sourceSchema) =>
            inner.MapSchema(sourceSchema);

        public TargetObjectIdentifier MapObject(InventoryObject source) =>
            inner.MapObject(source);

        public string MapChildIdentifier(
            InventoryObjectId ownerId,
            string objectType,
            string sourceSchema,
            string sourceName) =>
            inner.MapChildIdentifier(ownerId, objectType, sourceSchema, sourceName);

        public string QuoteIdentifier(string identifier) =>
            inner.QuoteIdentifier(identifier);

        public IReadOnlyList<IdentifierMappingEntry> Mappings =>
            inner.Mappings.Where(item =>
                item.SourceKey.ObjectId != missingObjectId).ToArray();
    }

    private static InventorySnapshot CreateInventory()
    {
        var schema = Object(InventoryObjectType.Schema, string.Empty, "dbo", 1, null);
        var table = Object(InventoryObjectType.Table, "dbo", "Customer", 2, null);
        var primaryKey = Object(InventoryObjectType.PrimaryKey, "dbo", "PK_Customer", 3, table.Id);
        var index = Object(InventoryObjectType.Index, "dbo", "IX_Customer_Name", 4, table.Id);
        var sequence = Object(InventoryObjectType.Sequence, "dbo", "OrderNumber", 5, null);
        var view = Object(
            InventoryObjectType.View,
            "dbo",
            "CustomerTop",
            6,
            null,
            "CREATE VIEW [dbo].[CustomerTop] AS SELECT TOP 5 [CustomerId], ISNULL([Name], N'') AS [Name] FROM [dbo].[Customer];");
        var synonym = Object(
            InventoryObjectType.Synonym,
            "dbo",
            "RemoteCustomer",
            7,
            null,
            "CREATE SYNONYM [dbo].[RemoteCustomer] FOR [OtherDb].[dbo].[Customer];");
        var trigger = Object(
            InventoryObjectType.Trigger,
            "dbo",
            "TRG_DigiPay_TrainerDetailsHistory_Del",
            8,
            table.Id,
            "CREATE TRIGGER [dbo].[TRG_DigiPay_TrainerDetailsHistory_Del] ON [dbo].[Customer] AFTER DELETE AS BEGIN SELECT 1; END");
        var objects = new[] { schema, table, primaryKey, index, sequence, view, synonym, trigger };
        var columns = new[]
        {
            Column(table, 1, "CustomerId", "int", false, true, null, "1", "1"),
            Column(table, 2, "Name", "nvarchar", false, false, "N'Unknown'", null, null, 200),
            Column(table, 3, "DisplayLength", "int", true, false, null, null, null, 4, true, "LEN([Name])")
        };
        var module = new ModuleInventory(
            view.Id, ModuleKind.View, true, true, false, false, false, false, null,
            false, false, false, false, [], []);
        var triggerModule = new ModuleInventory(
            trigger.Id, ModuleKind.DmlTrigger, true, true, false, false, false, false, null,
            false, false, false, false, [], []);

        return TestInventory.CreateSnapshot(objects) with
        {
            Schemas = [new SchemaInventory(schema, "dbo", objects.Length - 1, false, true)],
            Tables =
            [
                new TableInventory(
                    table.Id, TableKind.Ordinary, false, null, false, 0, null, false, false, false,
                    false, false, false, false, 10, 8192, 4096, [])
            ],
            Columns = columns,
            Constraints =
            [
                new ConstraintInventory(
                    primaryKey.Id, table.Id, ConstraintKind.PrimaryKey, primaryKey.SourceName,
                    [new ConstraintColumn(1, "CustomerId", false)], null, [], null, null, null,
                    false, false, false, true, "PRIMARY", 0, null)
            ],
            Indexes =
            [
                new IndexInventory(
                    index.Id, table.Id, 2, index.SourceName, IndexKind.NonClustered, false, false,
                    false, false, false, null, 0, null,
                    [new IndexColumn(1, "Name", false, false), new IndexColumn(0, "CustomerId", false, true)],
                    [], ConversionClassification.Automatic)
            ],
            Sequences =
            [
                new SequenceInventory(
                    sequence.Id, "sys", "bigint", 1000, 1, long.MinValue, long.MaxValue, false, 50, 1000, false)
            ],
            Modules = [module, triggerModule],
            Dependencies =
            [
                new InventoryDependency(view.Id, table.Id, DependencyKind.SqlExpression, table.QualifiedSourceName, true, false)
            ]
        };
    }

    private static InventoryObject Object(
        InventoryObjectType type,
        string schema,
        string name,
        int sqlId,
        InventoryObjectId? parent,
        string? definition = null)
    {
        var id = InventoryObjectId.Create("fixture", type, schema, name, sqlId, parent);
        return new InventoryObject(
            id, "fixture", schema, name,
            schema.Length == 0 ? $"[{name}]" : $"[{schema}].[{name}]",
            type, sqlId, parent, null, null, false, true, SelectionReason.CompleteDatabase, 0, 0, [],
            InventoryClassification.ForObject(type), definition, null, $"hash-{sqlId}", [],
            DiscoveryStatus.Discovered);
    }

    private static ColumnInventory Column(
        InventoryObject table,
        int ordinal,
        string name,
        string type,
        bool nullable,
        bool identity,
        string? defaultDefinition,
        string? seed,
        string? increment,
        short length = 4,
        bool computed = false,
        string? computedDefinition = null) =>
        new(
            InventoryObjectId.Create("fixture", InventoryObjectType.Column, table.SourceSchema, name, ordinal, table.Id),
            table.Id, ordinal, ordinal, name, type, type, "sys", length, 18, 0, null, nullable,
            identity,
            seed is null ? null : decimal.Parse(seed, System.Globalization.CultureInfo.InvariantCulture),
            increment is null ? null : decimal.Parse(increment, System.Globalization.CultureInfo.InvariantCulture),
            null, false, computed, computedDefinition, computed, computed ? true : null, false, false,
            false, false, 0, false, false, null, null, null, null, null, null, defaultDefinition,
            null, []);
}
